# Generated by Django 2.1.2 on 2018-10-28 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/artist/')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('artist_class', models.ManyToManyField(to='EventCreator.ArtistClass')),
            ],
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('decoration', models.ManyToManyField(to='EventCreator.Decoration')),
            ],
        ),
        migrations.CreateModel(
            name='LocationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/location/')),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventCreator.EventLocation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_first_name', models.CharField(max_length=100)),
                ('p_last_name', models.CharField(max_length=100)),
                ('p_phone', models.CharField(max_length=100)),
                ('p_email', models.EmailField(max_length=100)),
                ('event_time', models.DateTimeField(max_length=100)),
                ('id_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventCreator.Artist')),
                ('id_decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventCreator.Decoration')),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventCreator.Event')),
                ('id_location_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventCreator.LocationAddress')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.ManyToManyField(to='EventCreator.EventLocation'),
        ),
        migrations.AddField(
            model_name='artist',
            name='id_artist_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventCreator.ArtistClass'),
        ),
    ]
