# Generated by Django 2.1.2 on 2018-11-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCreator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='price',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='decoration',
            name='image',
            field=models.ImageField(null=True, upload_to='images/decorations/'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='price',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='locationaddress',
            name='price',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(null=True, upload_to='images/artist/'),
        ),
        migrations.AlterField(
            model_name='locationaddress',
            name='image',
            field=models.ImageField(null=True, upload_to='images/location/'),
        ),
    ]
